apiVersion: v1
kind: Service
metadata:
  name: mfe-lab
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "neoxs-me.labels" . | nindent 4 }}
    app.kubernetes.io/component: mfe-lab
spec:
  type: ClusterIP
  selector:
    {{- include "neoxs-me.selectorLabels" (dict "name" "mfe-lab" "Release" .Release) | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.mfeLab.port }}
      targetPort: {{ .Values.mfeLab.port }}
      protocol: TCP
